# Generated by Django 5.1.5 on 2025-01-16 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_assignment_description_en_assignment_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='teacher_about_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_about', to='course_app.teacher'),
        ),
        migrations.AddField(
            model_name='about',
            name='teacher_about_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_about', to='course_app.teacher'),
        ),
    ]
