# Generated by Django 5.1.5 on 2025-01-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_remove_answer_answer_answer_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examstudent',
            name='answer',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
