# Generated by Django 5.1.5 on 2025-01-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_about_teacher_about_en_about_teacher_about_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Teacher'},
        ),
    ]
