# Generated by Django 5.1.5 on 2025-01-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_student_options_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_app.student'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson', to='course_app.course'),
        ),
    ]
