# Generated by Django 5.1.5 on 2025-01-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_student_options_alter_teacher_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_user',
        ),
    ]
