# Generated by Django 5.1.5 on 2025-01-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_remove_student_student_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='teacher_about_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='teacher_about_ru',
        ),
    ]
